build:
  environment:
    php:
      version: 7.0
      ini:
        'date.timezone': 'Europe/Berlin'
  dependencies:
    before:
      - pecl install ssh-beta
  tests:
    override:
      -
    command: ./vendor/bin/phpunit --coverage-clover=my-coverage-file
    coverage:
      file: my-coverage-file
      format: php-clover
filter:
    excluded_paths:
        - tests/*
